default_agent: enquiry-mgmt
agents:
  enquiry-mgmt:
    name: lato_enquiry_mgmt
    entrypoint: src/enquiry_mgmt.py
    deployment_type: container
    runtime_type: null
    platform: linux/amd64
    container_runtime: null
    source_path: null
    aws:
      execution_role: arn:aws:iam::770071634381:role/AmazonBedrockAgentCoreSDKRuntime-eu-west-1-39396c42bd
      execution_role_auto_create: false
      account: '770071634381'
      region: eu-west-1
      ecr_repository: 770071634381.dkr.ecr.eu-west-1.amazonaws.com/bedrock-agentcore-lato_enquiry_mgmt
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: lato_enquiry_mgmt-6EIknFF5l6
      agent_arn: arn:aws:bedrock-agentcore:eu-west-1:770071634381:runtime/lato_enquiry_mgmt-6EIknFF5l6
      agent_session_id: d52bd73b-4660-4549-8fab-c137f38e175b
    codebuild:
      project_name: bedrock-agentcore-lato_enquiry_mgmt-builder
      execution_role: arn:aws:iam::770071634381:role/AmazonBedrockAgentCoreSDKCodeBuild-eu-west-1-39396c42bd
      source_bucket: bedrock-agentcore-codebuild-sources-770071634381-eu-west-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration:
      workload_name: workload-95b68750
      userId: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  return_request:
    name: return_request
    entrypoint: C:/Users/Joe.Robertson/Documents/Projects/lato-agent-langchain/latoagentcore/src/return_request_agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: null
    aws:
      execution_role: arn:aws:iam::770071634381:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-7b4091f4bb
      execution_role_auto_create: false
      account: '770071634381'
      region: us-east-1
      ecr_repository: 770071634381.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-return_request
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: return_request-XMdRNYA3CY
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:770071634381:runtime/return_request-XMdRNYA3CY
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-return_request-builder
      execution_role: arn:aws:iam::770071634381:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-7b4091f4bb
      source_bucket: bedrock-agentcore-codebuild-sources-770071634381-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  lato_enquiry_mgmt:
    name: lato_enquiry_mgmt
    entrypoint: src/enquiry_mgmt.py
    deployment_type: container
    runtime_type: null
    platform: linux/amd64
    container_runtime: null
    source_path: null
    aws:
      execution_role: arn:aws:iam::770071634381:role/AmazonBedrockAgentCoreSDKRuntime-eu-west-1-39396c42bd
      execution_role_auto_create: false
      account: '770071634381'
      region: eu-west-1
      ecr_repository: 770071634381.dkr.ecr.eu-west-1.amazonaws.com/bedrock-agentcore-lato_enquiry_mgmt
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: lato_enquiry_mgmt-6EIknFF5l6
      agent_arn: arn:aws:bedrock-agentcore:eu-west-1:770071634381:runtime/lato_enquiry_mgmt-6EIknFF5l6
      agent_session_id: d52bd73b-4660-4549-8fab-c137f38e175b
    codebuild:
      project_name: bedrock-agentcore-lato_enquiry_mgmt-builder
      execution_role: arn:aws:iam::770071634381:role/AmazonBedrockAgentCoreSDKCodeBuild-eu-west-1-39396c42bd
      source_bucket: bedrock-agentcore-codebuild-sources-770071634381-eu-west-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration:
      workload_name: workload-95b68750
      userId: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
